trigger:
- master

pool: "default"

steps:
- task: PowerShell@2
  displayName: Exécuter le script de déploiement
  inputs:
    targetType: 'filePath'
    filePath: '$(System.DefaultWorkingDirectory)/ScriptShellTP1.sh'

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
- task: Npm@1
  inputs:
    command: 'install' # installation des dépendances
    workingDir: '$(System.DefaultWorkingDirectory)'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(System.DefaultWorkingDirectory)'
    customCommand: 'run build' # compilation du projet
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(System.DefaultWorkingDirectory)'
    customCommand: 'run test' # lancement des tests