trigger:
- master

pool: "default"

steps:
- task: Bash@3
  displayName: Exécuter le script de déploiement
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/Site/ScriptShellTP1.sh'

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
- task: Npm@1
  displayName: Installer les dépendances
  inputs:
    command: 'install'
    workingDir: '$(System.DefaultWorkingDirectory)/Site/r301-js-movies'
- task: Npm@1
  displayName: Compiler le projet
  inputs:
    command: 'custom'
    workingDir: '$(System.DefaultWorkingDirectory)/Site/r301-js-movies'
    customCommand: 'run build'
- task: Npm@1
  displayName: Lancer les tests
  inputs:
    command: 'custom'
    workingDir: '$(System.DefaultWorkingDirectory)/Site/r301-js-movies'
    customCommand: 'run test'